tombuildsstuff/giovanni

- storage/2017-07-29/file/shares/properties_get.go
- storage/2018-03-28/file/shares/properties_get.go
- storage/2018-11-09/file/shares/properties_get.go
When retrieving the properties for a Share which has been deleted, the Quota header isn't returned, which results in the following error:
```
shares.Client#GetProperties: Failure responding to request: StatusCode=404 -- Original Error: Error converting "" to an integer: %!s(<nil>)
```
This PR conditionally parses the Quota value from the header providing it's not an empty string
> shares: conditionally parsing the quota

- storage/2018-03-28/queue/queues/lifecycle_test.go
- storage/2018-03-28/queue/queues/models.go
- storage/2018-11-09/queue/queues/lifecycle_test.go
- storage/2018-11-09/queue/queues/models.go
Adding ability to set and remove multiple cors rules. The API allows for 5 to be set. 
```
--- PASS: TestQueuesLifecycle (89.84s)
--- PASS: TestParseResourceID (0.00s)
```
> Add multiple cors rules

- storage/2018-03-28/queue/queues/properties_get.go
- storage/2018-11-09/queue/queues/properties_get.go
- version/version.go
Turns out that https://github.com/Azure/go-autorest doesn't automatically specify a path of `/` if one isn't specified - which means the strings computed for the authentication header can be wrong - since we were producing:
```
GET
application/xml; charset=utf-8
x-ms-date:Wed, 21 Aug 2019 11:53:48 GMT
x-ms-version:2018-11-09
/unlikely23exst2accti1t0?comp=properties
```
when Azure was expecting:
```
GET
application/xml; charset=utf-8
x-ms-date:Wed, 21 Aug 2019 11:53:48 GMT
x-ms-version:2018-11-09
/unlikely23exst2accti1t0/?comp=properties
```
(note the missing `/`)
This PR adds a default path of `/` to the `GetServiceProperties` method in the QueuesClient so that this works as expected
This bug only affects when using a SharedKeyLite to authenticate, which is why we didn't see this before
> Queues: specifying a path parameter

- storage/2018-03-28/queue/queues/properties_set.go
- storage/2018-11-09/queue/queues/properties_set.go
- version/version.go
Same as #4 this bug only shows when using a SharedKey to authenticate, since the URL is different to what the Azure Storage API's are expecting
> queues: setting a path for properties

- storage/2017-07-29/blob/blobs/append_block.go
- storage/2017-07-29/blob/blobs/put_block.go
- storage/2017-07-29/blob/blobs/put_block_blob.go
- storage/2017-07-29/blob/blobs/put_page_update.go
- storage/2017-07-29/file/files/range_put.go
- storage/2018-03-28/blob/blobs/append_block.go
- storage/2018-03-28/blob/blobs/put_block.go
- storage/2018-03-28/blob/blobs/put_block_blob.go
- storage/2018-03-28/blob/blobs/put_page_update.go
- storage/2018-03-28/file/files/range_put.go
- storage/2018-11-09/blob/blobs/append_block.go
- storage/2018-11-09/blob/blobs/put_block.go
- storage/2018-11-09/blob/blobs/put_block_blob.go
- storage/2018-11-09/blob/blobs/put_page_update.go
- storage/2018-11-09/file/files/range_put.go
Whilst this is inadvertently set via the `autorest.WithBytes` method
this PR forces this value to be set, so that this can be used for
building the SharedKey auth header
> Explicitly setting the Content-Length header when content is provided

- storage/2017-07-29/table/entities/query.go
- storage/2018-03-28/table/entities/query.go
- storage/2018-11-09/table/entities/query.go
Hi,
in our project we want to **query** Azure Tables. For querying the collection one must [request Table API](https://docs.microsoft.com/en-us/rest/api/storageservices/query-entities) with `$filter`  URL parameter.
In original code of the library there are two bugs:
1. wrong name of URL parameter - `filter`, must be `$filter`
2. wrong assignment of the value - value of the pointer must be referenced via `*` operator
I'm sending you the pull request to correct both bugs. Hope you merge and release it soon, it would help our team.
> Fix setting $filter in QueryPreparer

- storage/2017-07-29/table/entities/query.go
- storage/2018-03-28/table/entities/query.go
- storage/2018-11-09/table/entities/query.go
Hi,
when querying Azure Table **collection** you can configure optional URL parameter `$top` which is defacto a limit parameter (know for example from SQL).
With this you can limit number of returned table entities.
In this simple pull request I added code for configuring `$top` parameter in table queries.
> Add $top (limit) configuration to QueryEntitiesInput

- storage/2018-11-09/blob/containers/resource_id.go
- storage/2018-11-09/blob/containers/resource_id_test.go
- storage/2018-11-09/file/shares/resource_id.go
- storage/2018-11-09/file/shares/resource_id_test.go
This PR introduces a couple of methods to the Containers & Shares SDK's to get the Resource Manager ID for these resources. This is required since these resources can be referenced/managed by either the Data Plane API's or the Resource Manager API's
> containers/shares: adding methods to get the Resource Manager ID

- go.mod
- go.sum
- storage/2018-11-09/datalakestore/paths/client.go
- storage/2018-11-09/datalakestore/paths/create.go
- storage/2018-11-09/datalakestore/paths/create_test.go
- storage/2018-11-09/datalakestore/paths/delete.go
- storage/2018-11-09/datalakestore/paths/helpers.go
- storage/2018-11-09/datalakestore/paths/lifecycle_test.go
- storage/2018-11-09/datalakestore/paths/properties_get.go
- storage/2018-11-09/datalakestore/paths/properties_set.go
- storage/2018-11-09/datalakestore/paths/resource_id.go
- storage/2018-11-09/datalakestore/paths/resource_id_test.go
- storage/2018-11-09/datalakestore/paths/version.go
- storage/accesscontrol/ace.go
- storage/accesscontrol/ace_test.go
- storage/accesscontrol/acl.go
- storage/accesscontrol/acl_test.go
- testhelpers/client.go
Initial implementation of [Path API](https://docs.microsoft.com/en-gb/rest/api/storageservices/datalakestoragegen2/path) (for directory creation) to support https://github.com/terraform-providers/terraform-provider-azurerm/issues/7118
> Add support for directory creation in ADLS accounts

- storage/2018-11-09/datalakestore/paths/delete.go
- storage/2018-11-09/datalakestore/paths/lifecycle_test.go
- storage/2018-11-09/datalakestore/paths/properties_get.go
* Add path deletion step to ADLS path lifecycle test
* Fix `DeleteResponder` to expect StatusOK (`200`) as per [the docs](https://docs.microsoft.com/en-gb/rest/api/storageservices/datalakestoragegen2/path/delete#response)
* Add a check that a non-existent path returns an error from `GetProperties`
* Fix `GetProperties` to return the API response error
Fixes #32
> Fix ADLS Path Deletion

- storage/2019-12-12/file/files/lifecycle_test.go
- storage/2019-12-12/file/files/properties_set.go
This PR allows setting metadata in the properties set function and fixes an issue where a required header was missing when content-length wasn't specified.
> 2019-12-12/files/file - update properties set attributes

- storage/2019-12-12/file/files/properties_get.go
Hi! This is to address issue terraform-providers/terraform-provider-azurerm#10888. Pasting my comment here from the [issue tracker](https://github.com/terraform-providers/terraform-provider-azurerm/issues/10888#issuecomment-847565100):
> Hi. I looked a little into this and it seems that the return of GetProperties call in [storage_share_file_resource.go](https://github.com/terraform-providers/terraform-provider-azurerm/blob/2b30abb96725abae3c38e846bf1d8a1e2b0fcf2d/azurerm/internal/services/storage/storage_share_file_resource.go#L289) has an empty `ContentMD5`. I looked further in the Microsoft doc[1] and the function call in Giovanni storage SDK [2]. Giovanni uses response header `x-ms-content-md5` and according to the Microsoft doc, the `Range` or `x-ms-range` header must be set for this …
> fix for terraform-providers/terraform-provider-azurerm#10888

- storage/2020-08-04/table/tables/exists.go
1. API version is necessary here to make the API accepts the AAD Auth
2. The Accept json header is necessary here since otherwise the returned
xml is in atom format, in which case the autorest will fail to parse.
This PR is related with hashicorp/terraform-provider-azurerm#15083
> Table exists API add api version and accept json

- storage/2017-07-29/queue/queues/models.go
- storage/2018-03-28/queue/queues/models.go
- storage/2018-11-09/queue/queues/models.go
- storage/2019-12-12/queue/queues/models.go
- storage/2020-08-04/queue/queues/models.go
The retention policy days is not allowed to be set when retention policy is disabled.
E.g. when sending following request:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<StorageServiceProperties>
<Logging>
<Version>1.0</Version>
<Delete>false</Delete>
<Read>false</Read>
<Write>false</Write>
<RetentionPolicy>
<Enabled>false</Enabled>
<Days>7</Days>
</RetentionPolicy>
</Logging>
<HourMetrics>
<Version>1.0</Version>
<Enabled>false</Enabled>
<RetentionPolicy>
<Enabled>false</Enabled>
<Days>7</Days>
</RetentionPolicy>
</HourMetrics>
<MinuteMetrics>
<Version>1.0</Version>
<Enabled>false</Enabled>
<RetentionPolicy>
<Enabled>true</Enabled>
<Days>7</Days>
</RetentionPolicy>
</MinuteMetrics>
<Cors />
</StorageServiceProperties>
```
The API returns:
```
﻿<?xml version="1.0" …
```
> storage queue: xml encoding omity empty for retention policy `days`

- .gitignore
- storage/2020-08-04/file/files/range_put_file.go
> `files.(Client).PutFile`: return error when Put an empty file

- storage/2023-11-03/blob/blobs/append_block.go
- storage/2023-11-03/blob/blobs/copy.go
- storage/2023-11-03/blob/blobs/properties_get.go
- storage/2023-11-03/blob/blobs/put_append_blob.go
- storage/2023-11-03/blob/blobs/put_block.go
- storage/2023-11-03/blob/blobs/put_block_blob.go
- storage/2023-11-03/blob/blobs/put_block_list.go
- storage/2023-11-03/blob/blobs/put_block_url.go
- storage/2023-11-03/blob/blobs/put_page_blob.go
- storage/2023-11-03/blob/blobs/put_page_clear.go
- storage/2023-11-03/blob/blobs/put_page_update.go
- storage/2023-11-03/blob/blobs/snapshot.go
- storage/2023-11-03/blob/containers/create.go
- storage/2023-11-03/blob/containers/get_properties.go
- storage/2023-11-03/blob/containers/models.go
> blob, container: support for encryption scope

- storage/2023-11-03/file/directories/client.go
- storage/2023-11-03/file/files/client.go
Intentionally avoid setting this header when using shared key authentication, as the docs are ambiguous and it will avoid breaking existing users. The header seems to be required regardless of RBAC permissions granted.
<br>  <br>
> bugfix: add `x-ms-file-request-intent` header for the Files API when authenticating using OAuth

- storage/2023-11-03/blob/blobs/append_block.go
- storage/2023-11-03/blob/blobs/copy.go
- storage/2023-11-03/blob/blobs/get_block_list.go
- storage/2023-11-03/blob/blobs/get_page_ranges.go
- storage/2023-11-03/blob/blobs/lease_acquire.go
- storage/2023-11-03/blob/blobs/lease_change.go
- storage/2023-11-03/blob/blobs/properties_get.go
- storage/2023-11-03/blob/blobs/put_block_list.go
- storage/2023-11-03/blob/blobs/put_block_url.go
- storage/2023-11-03/blob/blobs/put_page_update.go
- storage/2023-11-03/blob/blobs/snapshot.go
- storage/2023-11-03/blob/blobs/snapshot_get_properties.go
- storage/2023-11-03/blob/containers/get_properties.go
- storage/2023-11-03/blob/containers/lease_acquire.go
- storage/2023-11-03/blob/containers/lease_break.go
- storage/2023-11-03/blob/containers/lease_change.go
- storage/2023-11-03/datalakestore/filesystems/properties_get.go
- storage/2023-11-03/datalakestore/paths/properties_get.go
- storage/2023-11-03/file/directories/get.go
- storage/2023-11-03/file/directories/metadata_get.go
- storage/2023-11-03/file/files/copy.go
- storage/2023-11-03/file/files/metadata_get.go
- storage/2023-11-03/file/files/properties_get.go
- storage/2023-11-03/file/shares/metadata_get.go
- storage/2023-11-03/file/shares/properties_get.go
- storage/2023-11-03/file/shares/snapshot_create.go
- storage/2023-11-03/file/shares/snapshot_get.go
- storage/2023-11-03/queue/queues/metadata_get.go
Related: https://github.com/hashicorp/terraform-provider-azurerm/issues/25378
> bugfix: nil checks on resp.Response

- storage/2023-11-03/file/directories/delete.go
- storage/2023-11-03/file/directories/models.go
- storage/2023-11-03/file/files/delete.go
- storage/2023-11-03/file/files/metadata_set.go
- storage/2023-11-03/file/files/properties_get.go
- storage/2023-11-03/file/files/properties_set.go
- storage/2023-11-03/file/files/range_put.go
- storage/2023-11-03/file/files/resource_id.go
- Fix a bug where a blank path can result in double slashes in the resource ID string, which the API doesn't tolerate
- Fix various method bugs where the path is erroneously prefixed with an additional slash
- Add a retry function when deleting directories (sometimes files within can linger after deletion)
Related: https://github.com/hashicorp/terraform-provider-azurerm/issues/25353
> bugfix: path fixes for files/file, retryfunc for directory deletion

- storage/2023-11-03/file/shares/delete.go
- storage/2023-11-03/file/shares/lifecycle_test.go
This is a breaking change.
Reference: https://learn.microsoft.com/en-us/rest/api/storageservices/delete-share#request-headers
Related issue: https://github.com/hashicorp/terraform-provider-azurerm/issues/26408
> share change `deleteSnapshot` from bool to enum, to support `include` and `include-leased`
